CREATE TABLE `vacinacao`.`pessoa` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NOT NULL,
  `DATANASCIMENTO` VARCHAR(45) NOT NULL,
  `SEXO` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `TIPOPESSOA` VARCHAR(45) NULL,
  `NOTAVACINA` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE);
  
  CREATE TABLE `exemplos`.`vacina` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `PAISORIGEM` VARCHAR(100) NOT NULL,
  `ESTAGIO` VARCHAR(50) NOT NULL,
  `DATAPESQUISA` VARCHAR(45) NOT NULL,
  `PESQUISADOR` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);